-- 01

SELECT NOME, ANO FROM FILMES;

-- 02

SELECT NOME, ANO, DURACAO FROM FILMES ORDER BY ANO;

--03

SELECT NOME, ANO, DURACAO FROM FILMES WHERE NOME = 'De Volta para o Futuro';

--04

SELECT NOME, ANO, DURACAO FROM FILMES WHERE ANO = 1997;

--05

SELECT NOME, ANO, DURACAO FROM FILMES WHERE ANO > 2000;

--06

SELECT NOME, ANO, DURACAO FROM FILMES WHERE   DURACAO < 150 AND DURACAO > 100 ORDER BY DURACAO;

--07

SELECT ANO, COUNT(*) AS QUANTIDADE FROM FILMES group by ANO ORDER BY QUANTIDADE DESC;

--08

SELECT * FROM Atores WHERE Genero = 'M';

--09

SELECT * FROM Atores WHERE Genero = 'F' ORDER BY PrimeiroNome;

--10

SELECT * FROM FilmesGenero ORDER BY IdFilme -- NAO POSUUI TODOS OS FILMES COM SUAS CLASSIFICAÇOES VEIO INCOMPLETA

SELECT FILMES.NOME, GENEROS.GENERO FROM FILMES
INNER JOIN FilmesGenero ON FILMES.ID = FilmesGenero.IdFilme
INNER JOIN Generos ON FilmesGenero.Id = GENEROS.ID
ORDER BY GENEROS.Genero, FILMES.NOME;


--11

SELECT FILMES.NOME, GENEROS.GENERO FROM FILMES
INNER JOIN FilmesGenero ON FILMES.ID = FilmesGenero.IdFilme
INNER JOIN Generos ON FilmesGenero.Id = GENEROS.ID
WHERE GENEROS.GENERO = 'Mistério'
ORDER BY GENEROS.Genero, FILMES.NOME

--12

SELECT FILMES.NOME, ATORES.PrimeiroNome, Atores.UltimoNome, ElencoFilme.Papel FROM FILMES
INNER JOIN ElencoFilme ON FILMES.ID = ElencoFilme.IdFilme
INNER JOIN Atores ON ElencoFilme.IdAtor = ATORES.ID
